/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Loan {
  'id' : bigint,
  'repaid' : boolean,
  'principal' : LoanAmount,
  'totalRepaidAmount' : LoanAmount,
  'owner' : Principal,
  'dueDate' : Time,
  'borrower' : string,
  'dateGiven' : Time,
  'interestRate' : bigint,
  'outstandingBalance' : LoanAmount,
  'totalRepaymentAmount' : LoanAmount,
}
export interface LoanAmount { 'amount' : bigint }
export interface LoanSummary {
  'totalOutstanding' : LoanAmount,
  'totalLent' : LoanAmount,
  'totalRepaid' : LoanAmount,
}
export interface LoanUpdate {
  'repaid' : boolean,
  'loanId' : bigint,
  'outstandingBalance' : LoanAmount,
}
export interface Repayment {
  'date' : Time,
  'loanId' : bigint,
  'amount' : LoanAmount,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addLoan' : ActorMethod<[string, LoanAmount, bigint, Time], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllLoans' : ActorMethod<[], Array<Loan>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLoan' : ActorMethod<[bigint], [] | [Loan]>,
  'getLoanSummary' : ActorMethod<[], LoanSummary>,
  'getLoansByBorrower' : ActorMethod<[string], Array<Loan>>,
  'getRepayments' : ActorMethod<[bigint], Array<Repayment>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordRepayment' : ActorMethod<[bigint, LoanAmount], LoanUpdate>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTotalRepaid' : ActorMethod<[bigint, LoanAmount], LoanUpdate>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];