/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const LoanAmount = IDL.Record({ 'amount' : IDL.Nat64 });
export const Time = IDL.Int;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Loan = IDL.Record({
  'id' : IDL.Nat,
  'repaid' : IDL.Bool,
  'principal' : LoanAmount,
  'totalRepaidAmount' : LoanAmount,
  'owner' : IDL.Principal,
  'dueDate' : Time,
  'borrower' : IDL.Text,
  'dateGiven' : Time,
  'interestRate' : IDL.Nat64,
  'outstandingBalance' : LoanAmount,
  'totalRepaymentAmount' : LoanAmount,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LoanSummary = IDL.Record({
  'totalOutstanding' : LoanAmount,
  'totalLent' : LoanAmount,
  'totalRepaid' : LoanAmount,
});
export const Repayment = IDL.Record({
  'date' : Time,
  'loanId' : IDL.Nat,
  'amount' : LoanAmount,
});
export const LoanUpdate = IDL.Record({
  'repaid' : IDL.Bool,
  'loanId' : IDL.Nat,
  'outstandingBalance' : LoanAmount,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addLoan' : IDL.Func([IDL.Text, LoanAmount, IDL.Nat64, Time], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLoan' : IDL.Func([IDL.Nat], [IDL.Opt(Loan)], ['query']),
  'getLoanSummary' : IDL.Func([], [LoanSummary], ['query']),
  'getLoansByBorrower' : IDL.Func([IDL.Text], [IDL.Vec(Loan)], ['query']),
  'getRepayments' : IDL.Func([IDL.Nat], [IDL.Vec(Repayment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordRepayment' : IDL.Func([IDL.Nat, LoanAmount], [LoanUpdate], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTotalRepaid' : IDL.Func([IDL.Nat, LoanAmount], [LoanUpdate], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const LoanAmount = IDL.Record({ 'amount' : IDL.Nat64 });
  const Time = IDL.Int;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Loan = IDL.Record({
    'id' : IDL.Nat,
    'repaid' : IDL.Bool,
    'principal' : LoanAmount,
    'totalRepaidAmount' : LoanAmount,
    'owner' : IDL.Principal,
    'dueDate' : Time,
    'borrower' : IDL.Text,
    'dateGiven' : Time,
    'interestRate' : IDL.Nat64,
    'outstandingBalance' : LoanAmount,
    'totalRepaymentAmount' : LoanAmount,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LoanSummary = IDL.Record({
    'totalOutstanding' : LoanAmount,
    'totalLent' : LoanAmount,
    'totalRepaid' : LoanAmount,
  });
  const Repayment = IDL.Record({
    'date' : Time,
    'loanId' : IDL.Nat,
    'amount' : LoanAmount,
  });
  const LoanUpdate = IDL.Record({
    'repaid' : IDL.Bool,
    'loanId' : IDL.Nat,
    'outstandingBalance' : LoanAmount,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addLoan' : IDL.Func(
        [IDL.Text, LoanAmount, IDL.Nat64, Time],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllLoans' : IDL.Func([], [IDL.Vec(Loan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLoan' : IDL.Func([IDL.Nat], [IDL.Opt(Loan)], ['query']),
    'getLoanSummary' : IDL.Func([], [LoanSummary], ['query']),
    'getLoansByBorrower' : IDL.Func([IDL.Text], [IDL.Vec(Loan)], ['query']),
    'getRepayments' : IDL.Func([IDL.Nat], [IDL.Vec(Repayment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordRepayment' : IDL.Func([IDL.Nat, LoanAmount], [LoanUpdate], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTotalRepaid' : IDL.Func([IDL.Nat, LoanAmount], [LoanUpdate], []),
  });
};

export const init = ({ IDL }) => { return []; };